paths:
  /Livros:
    post:
      tags:
        - Livro
      summary: Create a new instance of the model and persist it into the data source.
      operationId: Livro.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
    patch:
      tags:
        - Livro
      summary: Patch an existing model instance or insert a new one into the data source.
      operationId: Livro.patchOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
    put:
      tags:
        - Livro
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: Livro.replaceOrCreate__put_Livros
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
    get:
      tags:
        - Livro
      summary: Find all instances of the model matched by filter from the data source.
      operationId: Livro.find
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: array
            items:
              $ref: '#/definitions/Livro'
      deprecated: false
  /Livros/replaceOrCreate:
    post:
      tags:
        - Livro
      summary: Replace an existing model instance or insert a new one into the data source.
      operationId: Livro.replaceOrCreate__post_Livros_replaceOrCreate
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
  /Livros/upsertWithWhere:
    post:
      tags:
        - Livro
      summary: Update an existing model instance or insert a new one into the data source based on the where criteria.
      operationId: Livro.upsertWithWhere
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
  '/Livros/{id}/exists':
    get:
      tags:
        - Livro
      summary: Check whether a model instance exists in the data source.
      operationId: 'Livro.exists__get_Livros_{id}_exists'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
  '/Livros/{id}':
    head:
      tags:
        - Livro
      summary: Check whether a model instance exists in the data source.
      operationId: 'Livro.exists__head_Livros_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              exists:
                type: boolean
      deprecated: false
    get:
      tags:
        - Livro
      summary: 'Find a model instance by {{id}} from the data source.'
      operationId: Livro.findById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: filter
          in: query
          description: 'Filter defining fields and include - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
    put:
      tags:
        - Livro
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'Livro.replaceById__put_Livros_{id}'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
    delete:
      tags:
        - Livro
      summary: 'Delete a model instance by {{id}} from the data source.'
      operationId: Livro.deleteById
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
      deprecated: false
    patch:
      tags:
        - Livro
      summary: Patch attributes for a model instance and persist it into the data source.
      operationId: Livro.prototype.patchAttributes
      parameters:
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Livro'
        - name: id
          in: path
          description: Livro id
          required: true
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
  '/Livros/{id}/replace':
    post:
      tags:
        - Livro
      summary: Replace attributes for a model instance and persist it into the data source.
      operationId: 'Livro.replaceById__post_Livros_{id}_replace'
      parameters:
        - name: id
          in: path
          description: Model id
          required: true
          type: string
          format: JSON
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
  /Livros/findOne:
    get:
      tags:
        - Livro
      summary: Find first instance of the model matched by filter from the data source.
      operationId: Livro.findOne
      parameters:
        - name: filter
          in: query
          description: 'Filter defining fields, where, include, order, offset, and limit - must be a JSON-encoded string ({"something":"value"})'
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            $ref: '#/definitions/Livro'
      deprecated: false
  /Livros/update:
    post:
      tags:
        - Livro
      summary: 'Update instances of the model matched by {{where}} from the data source.'
      operationId: Livro.updateAll
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
        - name: data
          in: body
          description: An object of model property name/value pairs
          required: false
          schema:
            description: An object of model property name/value pairs
            $ref: '#/definitions/Livro'
      responses:
        '200':
          description: Request was successful
          schema:
            description: Information related to the outcome of the operation
            type: object
            properties:
              count:
                description: The number of instances updated
                type: number
                format: double
      deprecated: false
  /Livros/count:
    get:
      tags:
        - Livro
      summary: Count instances of the model matched by where from the data source.
      operationId: Livro.count
      parameters:
        - name: where
          in: query
          description: Criteria to match model instances
          required: false
          type: string
          format: JSON
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              count:
                type: number
                format: double
      deprecated: false
  /Livros/status:
    get:
      tags:
        - Livros
      operationId: Livros.status
      parameters: []
      responses:
        '200':
          description: Request was successful
          schema:
            type: object
            properties:
              status:
                type: string
      deprecated: false
definitions:
  Livros:
    properties:
      titulo:
        type: string
      autor:
        type: string
      editora:
        type: string
      ano:
        type: number
        format: double
      qtde_paginas:
        type: number
        format: double
      localizacao:
        type: string
      codigo_barras:
        type: string
      id:
        type: number
        format: double
    required:
      - titulo
      - autor
      - editora
      - ano
      - qtde_paginas
      - localizacao
      - codigo_barras
    additionalProperties: false
  x-any:
    properties: {}
  Livro:
    properties:
      titulo:
        type: string
      autor:
        type: string
      editora:
        type: string
      ano:
        type: number
        format: double
      qtde_pessoas:
        type: number
        format: double
      localizacao:
        type: string
      codigo_barras:
        type: string
      id:
        type: number
        format: double
    required:
      - titulo
      - autor
      - editora
      - ano
      - qtde_pessoas
      - localizacao
      - codigo_barras
    additionalProperties: false
basePath: /api
swagger: '2.0'
info:
  x-ibm-name: indt_library
  version: 1.0.0
  title: INDT_LIBRARY
schemes:
  - https
host: $(catalog.host)
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  clientIdHeader:
    type: apiKey
    in: header
    name: X-IBM-Client-Id
  clientSecretHeader:
    in: header
    name: X-IBM-Client-Secret
    type: apiKey
security:
  - clientIdHeader: []
    clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  catalogs:
    apic-dev:
      properties:
        runtime-url: $(TARGET_URL)
    sb:
      properties:
        runtime-url: 'http://localhost:4001'
  assembly:
    execute:
      - invoke:
          target-url: $(runtime-url)$(request.path)$(request.search)
